config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to =>"homes#top"

  resources :cart_item, only: [:create, :destroy, :update, :index] 
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user 
  belongs_to :cart
  
  # 税込み単価の算出,item.rbに記載が
  def with_tax_price
      (price * 1.1).floor
  end
  
  # 小計の算出
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CareItemsController < ApplicationController
before_action :authenticate_user!


  def destroy_all
    current_user.cart_items.destroy_all
    redirect_to request.referer
  end

  def destory
      @cart_item.destroy
      redirect_to current_cart
  end

  def index
    @cart_item = Cartitem.new   #この記述はitem_detailのページにも記載,新規投稿のために使用
    @cart_items = current_user.cart_items #ログイン中のユーザに結びついたカートアイテムが欲しい
    @total = 0   #合計金額の算出に使用する変数
  end

  def create
    @cart_item = Cartitem.new(cart_item_params)
    @cart_item.user_id = current_user.id
    if current_user.cart_items.find_by(item_id :cart_item_params[:item_id] ) #カート内に同一商品が存在するか調べる
      @cart_item.amount = @cart_amount.amount + (cart_item_params[:amount]).to_i
      @cart_item.update(cart_item_params)
      redirect_to cart_items_path #投稿したらカートに遷移？
    else
      @cart_item.save
      redirect_to cart_items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to request.referer
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/care_items_helper.rb
module CareItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/care_items/_cart.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
　　　<th>小計</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.item.item_name %></td>
        <td><%= cart_item.item.with_tax_price %></td>　<!--仮にwith_tax_priceをcart_item.rbに記載した場合はitemが余計-->
        <td><%= render 'form_update', cart_item: cart_item , item: cart_item.item %></td> <!--　数量をカート内でも変更できるようにしたい　-->
        <td><%= cart_item.subtotal %></td>
        <td><%= link_to '削除する', cart_item, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
        <% @total +=  cart_item.subtotal %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/care_items/_form.html.erb
<!--cart_item:@cart_item, item:@item（そのページ、またはレコードの商品情報が欲しい-->

<%= form_with model: cart_item, local:true do |f| %>
  <div class="form-group">
    <%= f.hidden_field :item_id, value: item.id %>  <!--cart.itemに今回のページのitemのidを代入したい-->
  </div>
  <div class="form-group">
    <%= f.select :amount, *[1..9] class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "カートに入れる" class: 'btn btn-success' %>
  </div>
<% end %>

app/views/care_items/_form_create.html.erb
<!--cart_item:@cart_item, item:@item（そのページ、またはレコードの商品情報が欲しい-->

<%= form_with model: cart_item, local:true do |f| %>
  <div class="form-group">
    <%= f.hidden_field :item_id, value: item.id %>  <!--cart.itemに今回のページのitemのidを代入したい-->
  </div>
  <div class="form-group">
    <%= f.select :amount, *[1..9] class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "カートに入れる" class: 'btn btn-success' %>
  </div>
<% end %>

app/views/care_items/_form_update.html.erb
<%= form_with model: cart_item,  url: update_cart_item_path(cart_item.id), method: :patch, local:true do |f| %>
  <div class="form-group">
    <%= f.hidden_field :item_id, value: item.id %>  <!--cart.itemに今回のページのitemのidを代入したい-->
  </div>
  <div class="form-se">
    <%= f.select :amount, *[1..9] class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "変更" class: 'btn btn-success' %>
  </div>

app/views/care_items/index.html.erb
<h1>ショッピングカート</h1>

<%= button_to "カートを空にする", destroy_all_cart_item_index, method: :delete %>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TryCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>